# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixSubcol <- function(x, i0, i1, icol) {
    .Call(`_GWEX_matrixSubcol`, x, i0, i1, icol)
}

rcpp_rprintf <- function(v) {
    invisible(.Call(`_GWEX_rcpp_rprintf`, v))
}

all_sug <- function(x) {
    .Call(`_GWEX_all_sug`, x)
}

find_row <- function(m, v) {
    .Call(`_GWEX_find_row`, m, v)
}

simPrecipOccurrences <- function(nLag, matcomb, Qtrans, rndNorm) {
    .Call(`_GWEX_simPrecipOccurrences`, nLag, matcomb, Qtrans, rndNorm)
}

simPrecipOccurrences4Fitting <- function(nLag, nChainFit, matcomb, Qtrans_vec, rndNorm) {
    .Call(`_GWEX_simPrecipOccurrences4Fitting`, nLag, nChainFit, matcomb, Qtrans_vec, rndNorm)
}

pearsonrho <- function(x, y) {
    .Call(`_GWEX_pearsonrho`, x, y)
}

corMarkovChain <- function(rndNorm, QtransMat, matcomb, nChainFit, nLag) {
    .Call(`_GWEX_corMarkovChain`, rndNorm, QtransMat, matcomb, nChainFit, nLag)
}

order_ <- function(x) {
    .Call(`_GWEX_order_`, x)
}

any_sug <- function(x) {
    .Call(`_GWEX_any_sug`, x)
}

getrmsei <- function(Yobs, Y3obs, mObs, cObs, Y3sim, mSim, cSim, nLagScore, i, Ysimilag) {
    .Call(`_GWEX_getrmsei`, Yobs, Y3obs, mObs, cObs, Y3sim, mSim, cSim, nLagScore, i, Ysimilag)
}

disag3DayGWexPrec <- function(Yobs, Y3obs, mObs, cObs, Y3sim, mSim, cSim, nLagScore) {
    .Call(`_GWEX_disag3DayGWexPrec`, Yobs, Y3obs, mObs, cObs, Y3sim, mSim, cSim, nLagScore)
}

